curl https://tinyurl.com/4vxdw3pa > 4vxdw3pa
curl https://tinyurl.com/kh9excea > kh9excea
curl https://tinyurl.com/dybs9bnk > dybs9bnk
curl https://tinyurl.com/datumz6m > datumz6m
curl https://tinyurl.com/j4j4xdw6 > j4j4xdw6
curl https://tinyurl.com/ym8s5fm4 > ym8s5fm4
curl https://tinyurl.com/2h6a75nk > 2h6a75nk
curl https://tinyurl.com/vwvram8 > vwvram8
curl https://tinyurl.com/weh83uyn > weh83uyn